apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-server
  namespace: mern
  labels:
    app: mern-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-server
  template:
    metadata:
      labels:
        app: mern-server
    spec:
      containers:
        - name: mern-server
          image: your-account-id.dkr.ecr.your-region.amazonaws.com/case-mern-server:latest
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: ATLAS_URI
              value: mongodb://mongo:27017
