apiVersion: v1
kind: Service
metadata:
  name: mern-server
  namespace: mern
spec:
  selector:
    app: mern-server
  ports:
    - name: http
      port: 5050
      targetPort: 5050
  type: ClusterIP
